version: '3'

services:
  pgvector:
    image: ankane/pgvector
    container_name: residency_hackathon
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgvector-data:/var/lib/postgresql/data

  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4096M"

volumes:
  pgvector-data:
    driver: local

